version: '3.8'

services:

  sample:
    container_name: controle-vendas-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - "REACT_APP_API_URL=http://localhost:8080"